config/routes.rb
Rails.application.routes.draw do

  root to: "students#index"

  resources :students

end

app/models/student.rb
class Student < ActiveRecord::Base

  def self.find_min
    students = Student.all
    min_grade = students.map { |student| student[:grade] }.min
    min_grade
  end

  def self.find_max
    students = Student.all
    max_grade = students.map { |student| student[:grade] }.max
    max_grade
  end

  def self.find_average
    students = Student.all
    grades = students.map { |student| student[:grade] }
    average_grade = grades.inject{ |sum, el| sum + el }.to_f / grades.size
    average_grade
  end

  def self.set_status
    students = Student.all
    students.each do |student|
      if student.grade < 65
        student.update_attribute(:status, "red")
      else
        student.update_attribute(:status, "none")
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    students = Student.all
    @students = students.sort_by { |k| k["name"] }
    find_minimum_grade
    find_maximum_grade
    find_average_grade
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      set_student_status
      redirect_to root_path
    end
  end

  respond_to :json

  def update
    @student = Student.find params[:id]
    respond_to do |format|
      if @student.update_attributes(student_params)
        format.json { respond_with_bip(@student) }
        set_student_status
      else
      end
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to root_path
  end


  private

  def student_params
    params.require(:student).permit(:name, :grade)
  end

  def find_minimum_grade
    @minimum_grade = Student.find_min
  end

  def find_maximum_grade
    @maximum_grade = Student.find_max
  end

  def find_average_grade
    @average_grade = Student.find_average.round(2)
  end

  def set_student_status
    Student.set_status
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TeacherGradebookRuby</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>


</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Grade Book / Paul Wenig</a>
    </div>
  </div>
</nav>

<%= yield %>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<script src="../../dist/js/bootstrap.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>


</body>
</html>

app/views/students/index.html.erb
<div class="container" id="main-form">
  <div class="report">
    <h2>History Grades</h2>

    <table class="table table-bordered table-hover" id="report-table">
      <thead>
      <tr>
        <th>Student Name</th>
        <th>Grade</th>
        <th></th>
      </tr>
      </thead>
      <tbody>

      <% @students.each do |student| %>
        <tr style="background-color: <%= student.status %> ">
          <td><%= best_in_place student, :name %></td>
          <td><%= best_in_place student, :grade %></td>
          <td id="delete-student"><%= link_to "Delete", student_path(student), :method => :delete %></td>
        </tr>
      <% end %>

      <tr>
      <%= form_for(@student, :id => "student-form") do |f| %>
        <td><%= f.text_field :name, placeholder: 'Name' %></td>
        <td><%= f.text_field :grade, placeholder: 'Grade' %></td>
        <td><%= f.submit "Add Student" %></td>
      <% end %>
      </tr>
      </tbody>
    </table>

    <h3>Class Summary</h3>
    <h4>Min Grade: <%= @minimum_grade %> </h4>
    <h4>Max Grade: <%= @maximum_grade %> </h4>
    <h4>Average Grade: <%= @average_grade %> </h4>

  </div>
</div>

<script>
  jQuery(".best_in_place").best_in_place().bind("ajax:success", function () {location.reload(); });
</script>